#!/bin/sh
### TYPE: builtin
# Copy to '/home/pi/runCamera' to have FRC Vision RPi services to not run
# an application; useful for non-service managed development
# Make script executable on target platform
echo "Waiting 60 seconds..."
sleep 60
